# Tomcat 端口
server:
  port: 8080

spring:
  # Druid Pool 运行环境
  profiles:
    # 运 行 环 境
    active: druid

# mybatis 配置
mybatis:
  # 配 置 扫 描
  mapper-locations: classpath*:**/xml/**.xml
  # 别 名 扫 描
  type-aliases-package: com.pearadmin

# Pear 插 件 配 置 信 息
pear:
  plugin:
    logging:
      # 日 志 ID 的 生 成 方 式
      sequence:
        worker: 3
        center: 3
      # 是 否 开 启 日 志 记 录
      enable: true


# Page Helper
pagehelper:
  # 方 言
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# logging 配置
logging:
  # 日 志 级 别
  level:
    # 日 志 包 配 置
    com.pearadmin.*: DEBUG



