# Tomcat 端口
server:
  port: 8080

spring:
  # Druid Pool 运行环境
  profiles:
    active: druid
  banner: false

# mybatis 配置
mybatis:
  # 配置扫描
  mapper-locations: classpath*:**/xml/**.xml
  # 别名扫描
  type-aliases-package: com.pearadmin

# Pear 插 件 配 置 信 息
pear:
  plugin:
    logging:
      # 日 志 ID 的 生 成 方 式
      sequence:
        worker: 3
        center: 3
      # 是 否 开 启 日 志 记 录
      enable: true
    # Sequence 配 置 信 息
    sequence:
      # 数 据 中 心
      center-id: 1
      # 机 器 编 码
      worker-id: 1
      # 最 小 空 闲
      min-idle: 50
      # 初 始 化 数 量
      init-size: 360
    # Document 配 置 信 息
    document:
      # 文 档 标 题
      title: Pear Admin API
      # 是 否 开 启
      enable: true
      # 描 述 信 息
      describe: 企 业 快 速 开 发 平 台
      # 扫 包 路 径
      scan-package: com.pearadmin
      # 协 议
      licence: apache
      # 协 议 地 址
      licence-url: https://gitee.com/pear_community
      # 组 织 信 息
      terms-of-service-url: https://gitee.com/pear_community
      # 版 本 信 息
      version: Release 2.0.0
      # 扩 展 信 息
      contact:
        # 作 者
        name: 就 眠 仪 式
        # 连 接
        url: www.pearadmin.cn
        # 邮 箱
        email: Jmys1992@gmail.com

# pageHelper 配置
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# logging 配置
logging:
  level:
    # 日志级别
    com.pearadmin.*: DEBUG



