# Tomcat 端口
server:
  port: 9191

spring:
  # Druid Pool 运行环境
  profiles:
    active: druid

# mybatis 配置
mybatis:
  mapper-locations: classpath*:**/xml/**.xml
  type-aliases-package: com.pearadmin

# pageHelper 配置
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# logging 配置
logging:
  level:
    com.pearadmin.*: DEBUG
